# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
  pod  ‘MGIndexView’, '~> 0.0.1'
    pod 'SwiftyJSON'
    pod 'SVProgressHUD'
    # Swift
    pod 'Alamofire', '~> 4.2.0'           # 网络请求

end
