# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftyDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod "SkeletonView"
	pod 'SnapKit'
	pod 'Kingfisher'
  pod 'Alamofire'
  pod 'MJExtension'
  pod 'SVProgressHUD' # 请求的时候提示文字
  pod 'HandyJSON'
  pod 'SwiftyJSON','~> 4.2.0'

end
